### ISSUE TITLE
Mark terms as layperson in yaml template

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#210]
I would like to mark certain terms as layperson in the yaml pattern, such as Large [anatomy] synonym for increased size

**Comment by nicolevasilevsky** [comment]
is there a way we can do this?

**Comment by balhoff** [comment]
You ought to be able to, but actually I think there is a gap in the pattern schema here. @dosumis @cmungall as far as I can see there isn't a way to create an annotation (actually here an annotation of an annotation) with an IRI as the value.

**Comment by dosumis** [comment]
> I would like to mark certain terms as layperson in the yaml pattern, such as Large [anatomy] synonym for increased size. 

Not entirely sure what's being requested here.  I haven't (up to now) thought of the YAML design patterns as specifying rendering.  The whole pattern is intended to be converted to OWL.  Any way you choose to mark terms or synonyms has to fit with this + any other standards the target ontology conforms to (e.g. OBO annotation properties; OBO-style representation of synonyms.)

> As far as I can see there isn't a way to create an annotation (actually here an annotation of an annotation) with an IRI as the value.

Could pass IRI as string.  

Perhaps related:

Any list annotation can take a list of vars as a value.  Each var = an OWL entity.  The description doesn't properly specify what to do with these, but I think the OWL entity should become the target of the annotation.  (In the case of subsets, the entity is another AP; In LEGO individuals are used as the subjects of annotation axioms).

**Comment by pnrobinson** [comment]
btw I am not sure that "large" is always correct; probably "enlarged" is.

**Comment by dosumis** [comment]
Think I now know what you want.

In OBO:

synonym: 'enlarged' LAY_TERMINOLOGY EXACT [PMID:1234567]

I agree we need more general support for synonym types.  This would be legal if we allow APs to be specified in vars:

``` yaml

annotationProperties: 
   'has_synonym_type' : ...

vars:
   synonym_type:  AnnotationProperty    # Use this to specify LAY_TERMINOLOGY AP

data_list_vars:
    exact_lay_synonyms: 

exact_synonym:
    value: 
        exact_lay_synonyms
    annotations:
       - annotationProperty: has_synonym_type
       - value: synonym_type
    xrefs: 

```

For convenience, we could add an optional type annotation field to the OBO exact_synonym fields.   If you want to add non lay synonyms in the same pattern, you'd need to use the core spec though.
