### ISSUE TITLE
Question about this yaml pattern: abnormalMorphologyInLocation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#221]
https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalMorphologyInLocation

This is the example in the [google doc](https://docs.google.com/document/d/10NCd9jXGXA4BETSBxdbVGfDFM2w4gAIbY6vpm4ERTBo/edit#):
‘abnormal cardiomyocyte mitochondrion morphology’ [MP:xxxx]
'has part' some
	(morphology
 	and ('inheres in' some (mitochondrion and ‘part of’ some cardiomyocyte)))
 	and ('has modifier' some abnormal))

So it could be an abnormal cell part in a cell. My question is, is it okay to use entity twice for the vars (instead of something specific, like anatomical entity?)

**Comment by balhoff** [comment]
You will need to create two different variables, otherwise, the same value will be filled in so that you get something like:

"Morphological abnormality of the mitochondrion in the mitochondrion"

It's okay to have two different variables for which the range of values is the same (e.g. 'anatomical entity'). Do this instead:

```yaml
vars:
  entity: Thing
  location: Thing

name:
  text: "Morphological abnormality of the %s in the %s"
  vars:
   - entity
   - location
```
