### ISSUE TITLE
abnormal photoreceptor distance

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#305]
Hello,

I have a couple of phenotypes I am trying to model.  I have created a pattern but want to make sure I am approaching this correctly.

My phenotypes:
 - Photoreceptors that are too closely spaced  
 - Photoreceptors that are too distantly spaced  

I was thinking of using adduction and abduction to describe the abnormal position of the eyes in relation to the midline.

**adduction**  PATO:0002133
http://purl.obolibrary.org/obo/PATO_0002133
A displaced angular placement quality inhering in a body part by virtue of the bearer's movement closer the medial plane of the body.

**abduction**  PATO:0002131
http://purl.obolibrary.org/obo/PATO_0002131
A displaced angular placement quality inhering in a body part by virtue of the bearer's movement away from the medial plane of the body.

`'has_part' some ('adduction' and ('inheres_in' some 'photoreceptor') and ('qualifier' some 'abnormal'))`

`'has_part' some ('abduction' and ('inheres_in' some 'photoreceptor') and ('qualifier' some 'abnormal'))`

My proposed pattern and rules:
```
classes:
  position: PATO:0000140
  abnormal: PATO:0000460
  entity: BFO:0000001

equivalentTo:
  text: "'has_part' some (%s and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - position
    - entity
```

Thank you,
Sofia
