### ISSUE TITLE
Review: abnormalPathology

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#318]
[abnormalPathology.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalPathology.yaml)

The name does not match with the defined pattern. The pattern uses 'increased amount'. The title should be something along the lines of 'increasedAmountOfPathologyInAnatomicalEntity'

```
equivalentTo:
  text: "'has_part' some ('increased amount' and ('inheres_in' some %s) and ('part_of' some %s)) and ('qualifier' some abnormal)"
  vars:
    - pathological_entity
    - anatomical_structure
```
---

The name probably should be changed from
```
name:
  text: "%s %s"
```
to

```
name:
  text: "%s in the %s"
```
or something a bit nicer than one that will lead to names like "'cell and tissue damage' 'head'"

---

Also the class restrictions includes.
```
  anatomical structure: UBERON:0000061
```

Could the be `entity: BFO:0000001` instead?

Sofia
