### ISSUE TITLE
Review: abnormalLevelOfCellularComponent

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#319]
[abnormalLevelOfCellularComponent.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfCellularComponent.yaml)

Overall this pattern looks fine to me. There is only one minor issue in consistency, the synonym does not match the rest this pattern. Everywhere else there is only a mention of abnormal not elevated.

```
annotations:
  - annotationProperty: exact_synonym
    text: "Elevated %s"
    vars:
     - cellularcomponent
```

Sofia
