### ISSUE TITLE
Review: abnormalLevelOfChemicalInEntity

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#320]
[abnormalLevelOfChemicalInEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemicalInEntity.yaml)

abnormal should be quoted

```
equivalentTo:
  text: "'has_part' some (amount and ('inheres_in' some (%s and ('part_of' some %s))) and ('qualifier' some abnormal))"
  vars:
    - 'chemical entity'
    - entity
```

Sofia

**Comment by nicolevasilevsky** [comment]
I fixed this- thanks for catching that!

**Comment by ybradford** [comment]
This should be limited only continuant entities I believe. chemical would be a material entity, so it wouldn't be able to be part_of a process.

**Comment by matentzn** [comment]
@ybradford is right. I would go even further and say it should be an anatomical structure; What do you think?

**Comment by srengel** [comment]
I may be misunderstanding...are you suggesting that chemicals only be at abnormal levels in an anatomical structure? What about cellular structures?

**Comment by matentzn** [comment]
Woops, my bad. You are right of course. I kind of hoped cellular structures fall under anatomical ones. but probably not. Maybe @ybradford suggestion is closer then. I kind of want, however, to reduce our reliance on BFO. Maybe someone knows of a better all-encompassing term that reflects:
`bodily material entity` (to exclude the possibility of accidentally instantiating for example external entities such as viruses or similar).

**Comment by cmungall** [comment]
cells and cell components are anatomical entities

**Comment by cmungall** [comment]
re: reducing reliance on BFO. The OBO-Core effort will make this clearer. It will essentially provide a "biological upper level" where the top level classes will be anatomical structure, phenotype, disease, chemical entity, etc, rather than funny philosophical things

**Comment by matentzn** [comment]
Does this work for everyone? @obophenotype/phenotype-editors 

```
pattern_name: abnormalLevelOfChemicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalLevelOfChemicalEntityInLocation.yaml
description: ""

classes:
  amount: PATO:0000070
  abnormal: PATO:0000460
  chemical entity: CHEBI:24431
  anatomical entity: UBERON:0001062
   
relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

vars:
  chemical_entity: "'chemical entity'"
  location: "'anatomical entity'"

name:
  text: "abnormal %s %s level"
  vars:
   - location
   - chemical_entity


def:
  text: "An abnormal level of %s in the %s."
  vars:
    - chemical_entity
    - entity

equivalentTo:
  text: "'has_part' some (amount and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity
    - location
```

Good description also welcome.

**Comment by LCCarmody** [comment]
Looks good.

**Comment by ybradford** [comment]
this looks good

**Comment by chris-grove** [comment]
@matentzn 

In the stanza:

"""
def:
  text: "An abnormal level of %s in the %s."
  vars:
    - chemical_entity
    - entity
"""

shouldn't "- entity" either be "- location" or "- anatomical entity"? Or maybe that's irrelevant?

**Comment by chris-grove** [comment]
Also, does "amount" need to be in single quotes " 'amount' "  in the "equivalentTo:" statement?

**Comment by matentzn** [comment]
Okay, I have declared this to be final now. 

```
pattern_name: abnormalLevelOfChemicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalLevelOfChemicalEntityInLocation.yaml
description: "An abnormal level of a chemical in an anatomical entity, such as abnormal level of sodium in the blood."

contributors:
  - https://orcid.org/0000-0003-4606-0597
  - https://orcid.org/0000-0002-9900-7880
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0003-4148-4606
  - https://orcid.org/0000-0001-7941-2961
  - https://orcid.org/0000-0002-7356-1779
  - https://orcid.org/0000-0001-9076-6015

classes:
  amount: PATO:0000070
  abnormal: PATO:0000460
  chemical entity: CHEBI:24431
  anatomical entity: UBERON:0001062
   
relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

vars:
  chemical_entity: "'chemical entity'"
  location: "'anatomical entity'"

name:
  text: "abnormal %s %s level"
  vars:
   - location
   - chemical_entity

def:
  text: "An abnormal level of %s in the %s."
  vars:
    - chemical_entity
    - location

equivalentTo:
  text: "'has_part' some ('amount' and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity
    - location
```

Scream if there is an issue.
