### ISSUE TITLE
Review: abnormalProcessInALocation

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#321]
[abnormalProcessInALocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalProcessInALocation.yaml)

Title does not match the pattern. The pattern includes 'having extra processual parts' but the title is only abnormalProcess. This is super long, but maybe it should be something more like:
- extraProcessualPartsOfBiologicalProcessInLocation or
- extraProcessualPartsOfBiologicalProcessInAnatomicalEntity or
- extraPartsOfProcessInLocation

```
equivalentTo:
  text: "'has_part' some ('having extra processual parts' and ('inheres_in' some (%s and ('part_of' some %s))) and  ('qualifier' some 'abnormal'))"
  vars:
    - biological_process
    - entity
```

Sofia
