### ISSUE TITLE
Review: abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#323]
[decreasedFunctionalityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/decreasedFunctionalityInLocation.yaml)

'entity' is defined as a class and a variable but is not used.

```
classes:
  decreased functionality: PATO:0001624
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  entity: BFO:0000001


vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'entity'"
```

```
equivalentTo:
  text: "'has_part' some ('decreased functionality' and ('inheres_in' some %s)) and  ('qualifier' some 'abnormal')"
  vars:
    - anatomical_entity
```

Sofia

**Comment by pnrobinson** [comment]
Somehow I am not sure if this is the ideal term. Physiological functions sometimes relate to one organ but often relate to multiple ones, and so basing a functional abnormality hierarchy on organs is not necesarily a great idea. I know we have this currently in HPO but I think it needs discussion and improvement.

**Comment by nicolevasilevsky** [comment]
This pattern is also used with cell types currently in the HPO. For example:
HP_0006279 'Beta-cell dysfunction'

'has part' some 
('decreased functionality' and ('inheres in' some 'type B pancreatic cell') and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
The problem with terms like Beta-cell dysfunction is that they are an inference. We really see various functional abnormalities related to blood sugar and insulin etc., but we are not directly observing the beta cell. For better of worse, this is how some data are reported to us and so I am not sure that we can do without this term. However, at present at least, there is no logical bridge between the above logical definition and any of the actual functional problems that are represented in other places of the HPO, correct?

**Comment by nicolevasilevsky** [comment]
pattern_name: decreasedFunctionalityOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedFunctionalityOfAnatomicalEntityInLocation.yaml
description: ""

classes:
  decreased functionality: PATO:0001624
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'anatomical entity'"

name:
  text: "%s dysfunction"
  vars:
   - anatomical_entity

def:
  text: "A functional abnormality of the %s."
  vars:
   - anatomical_entity

equivalentTo:
  text: "'has_part' some ('decreased functionality' and ('inheres_in' some %s)) and  ('has_modifier' some 'abnormal')"
  vars:
    - anatomical_entity
 
@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
As I think @srobb1 alluded to, there are two variables declared, but only one actually used. I would actually like to have pattern called "abnormallyDecreasedFunctionalityOfAnatomicalEntity" with the logical definition above:

```
'has_part' some ('decreased functionality' and ('inheres_in' some %s)) and ('has_modifier' some 'abnormal')
vars:
- anatomical_entity
```

and a separate "abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation" pattern with the logical definition:

```
'has_part' some ('decreased functionality' and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))
vars:
- anatomical_entity
- location
```

**Comment by chris-grove** [comment]
OK, I'm going to change the label of the pattern from:

decreasedFunctionalityOfAnatomicalEntityInLocation

to:

decreasedFunctionalityOfAnatomicalEntity

**Comment by chris-grove** [comment]
Pattern as of June 10, 2019:
```
pattern_name: abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation.yaml
description: "An impaired function of an anatomical entity or part, in a specific anatomical location, such as Beta-cell dysfunction in the pancreas."

contributors:
- https://orcid.org/0000-0001-5208-3432
classes:
  decreased functionality: PATO:0001624
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  independent continuant: BFO:0000004

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'independent continuant'"

name:
  text: "%s dysfunction in %s"
  vars:
  - anatomical_entity
  - entity

def:
  text: "A functional abnormality of the %s in %s."
  vars:
  - anatomical_entity
  - entity

equivalentTo:
  text: "'has_part' some ('decreased functionality' and ('inheres_in' some (%s and ('part_of' some %s))) and  ('has_modifier' some 'abnormal')"
  vars:
  - anatomical_entity
  - entity
```

The pattern schema checker reports that the "part of" relation is not declared in this pattern (also in the "abnormallyIncreasedFunctionalityOfAnatomicalEntityInLocation.yaml" pattern). Need to add

```
relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050
```

to the declared relations list.
