### ISSUE TITLE
Review: delayedProcess

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#324]
[delayedProcess.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/delayedProcess.yaml)

Should the class 'entity' be 'biological_process' or something more restrictive?

```
classes:
  delayed: PATO:0000502
  abnormal: PATO:0000460
  entity: BFO:0000001

...

equivalentTo:
  text: "'has_part' some ('delayed' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - entity

```

Sofia
