### ISSUE TITLE
Review: increasedLevelOfMolecularEntityInLocation

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#326]
[increasedLevelOfMolecularEntityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedLevelOfMolecularEntityInLocation.yaml)

Synonym should be increased not reduced.

```
annotations:
  - annotationProperty: exact_synonym
    text: "reduced level of %s in %s"
    vars:
    - molecular_entity
    - location
```

Sofia
