### ISSUE TITLE
Review: abnormalBehavior.yaml

### ISSUE THREAD

**Issue by ybradford** [obophenotype/upheno#331]
[abnormalBehavior.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalBehavior.yaml)

For classes Behavior process is NBO behavior process. Does this mean that GO behavior processes are excluded? ZFIN uses GO for behavior currently (swimming behavior  GO:0036269, locomotory behavior GO:0007626 for example). Maybe ZFIN will need to consider moving to NBO, but restricting to NBO right now will mean ZP behaviors will be done as processes. Maybe that is ok, but these should be considered for reconciliation.

**Comment by nicolevasilevsky** [comment]
This wasn't intentional, @ybradford, we should revise the pattern to include GO behaviors.

**Comment by matentzn** [comment]
this will be captured by OBO core hopefully. Both GO and NBO behaviour must be usable for behavior patterns!

**Comment by sbello** [comment]
Looking at the MP patterns we have terms that use NBO, terms that use GO (MP:0001422 for example), and a few terms that use UBERON (MP:0004262, MP:0009434). The ones I've found using UBERON relate to strength or paralysis. So I think we're going to need to review and potentially broaden the parent pattern.

**Comment by matentzn** [comment]
```
pattern_name: abnormalBehavior
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBehavior.yaml
description: "Any unspecified abnormality of a behavior."

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  behavior process: NBO:0000313

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  behavior_process: "'behavior process'"
 
name:
  text: "abnormal %s"
  vars:
   - behavior_process

def:
  text: "An anomaly in %s."
  vars:
    - behavior_process

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - behavior_process
```
@obophenotype/phenotype-editors please sign off
