### ISSUE TITLE
Review: abnormalAnatomicalEntity

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#367]
```
pattern_name: abnormalAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalAnatomicalEntity.yaml
description: "Any unspecified abnormality of an anatomical entity."

contributors:
  - https://orcid.org/0000-0002-9900-7880
  - https://orcid.org/0000-0001-9076-6015
  - https://orcid.org/0000-0003-4148-4606
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0002-7356-1779
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0001-7941-2961

classes:
  quality: PATO:0000001
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051
  
annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "abnormal %s"
  vars:
   - anatomical_entity

annotations:
  - annotationProperty: exact_synonym
    text: "abnormality of %s"
    vars:
     - anatomical_entity

def:
  text: "Abnormality of %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('quality' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```

Can you guys make give me a confirmative comment that this pattern is now final?
@obophenotype/phenotype-editors
