### ISSUE TITLE
Review: decreasedSizeOfAnatomicalEntity

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#370]
[decreasedSizeOfAnatomicalEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/decreasedSizeOfAnatomicalEntity.yaml)

I added contributors, description, and example term:
https://github.com/obophenotype/upheno/pull/369

I think this one might be done???

**Comment by matentzn** [comment]
```
pattern_name: decreasedSizeOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedSizeOfAnatomicalEntity.yaml
description: "Small entity, like a small anatomical structure.	MP_0020533 'decreased pons size'"

contributors:
  - https://orcid.org/0000-0002-9611-1279
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0002-7356-1779
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0003-4148-4606

classes:
  decreased size: PATO:0000587
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "decreased size of the %s"
  vars:
   - entity

annotations:
  - annotationProperty: exact_synonym
    text: "small %s"
    vars:
     - anatomical_entity

def:
  text: "A reduction in the size of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('decreased size' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```

@obophenotype/phenotype-editors

**Comment by matentzn** [comment]
"Small entity" a bit vague. I think it is "smaller than usual"?

**Comment by ybradford** [comment]
I agree 'smaller than usual' seems more appropriate.

**Comment by pnrobinson** [comment]
Smaller than usual is not abnormal -- I think 'Abnormally small' fits better with the definition.
For medical use in HPO, it is often preferable to say how something is too small -- do we have definitions for these use cases?

**Comment by matentzn** [comment]
@pnrobinson Can you give a few examples of ways in which something can be too small? We have too short, decreased width and so on.. But do you mean something else?

**Comment by ybradford** [comment]
@matentzn general question - will all the children of 'decreased size' have their own pattern? ZFIN would use this term for general comments about decreased size and would use more specific annotations to say what is different about the size (length, area, height, etc).

'Abnormally small' does reflect the intention of the pattern better than 'smaller than usual'.

**Comment by matentzn** [comment]
To be honest, this is one of the hierarchies in PATO that I find pretty broken. Decreased width does not imply decreased size in my humble opinion. It’s one of the topics for the next POTATO workshop. But yes; everything gets it’s own well documented pattern! Many are already there!

**Comment by ValWood** [comment]
I agree @mah did not model decreased or increased width of a cell to be related to decreased or increased size, because in this situation if you decrease a cell width the length usually increases proportionally. At the cellular level size and shape are largely independent. 

Obviously this isn't the case in anatomy, which is why the concepts of shape and size often get convoluted.

**Comment by pnrobinson** [comment]
In some medical contexts one distinguishes between different ways of being too small, e.g., a small nose both has a decreased height and a decreased width, and it is recommended to be that specific when using HPO or describing patients in journals. The terminology in medicine tends to be context specific, but I think PATO should have something for the 3 dimensions at least

**Comment by ValWood** [comment]
You almost need compound terms to model these specific types of "smallness"  accurately.

Small with decreased width
Small with decreased length

...as long as small is defined correctly. Small is decreased  size (i.e volume really). The decreased size may be achieved because one dimension is decreased, but this isn't always *necessarily* associated with a  size reduction.  So, you probably require explicit terms.

**Comment by mah11** [comment]
I think some inconsistency has crept into FYPO (fodder for review this summer), but we should maintain or restore patterns that state explicitly and specifically which cell dimension(s) is/are affected. 

Cell size should mean cell volume, and a change in one dimension that doesn't alter cell volume should be classified as a change in cell shape, but not cell size. That may not be totally intuitive (even to me, as I chug along editing FYPO), which is likely a source of any internal inconsistency we've got now.

IOW, I pretty much agree with Val, but I might suggest avoiding labels like "small with decreased width" precisely because they're open to misinterpretation. If size = volume globally, then use "decreased volume and decreased width".

**Comment by mah11** [comment]
p.s. It's probably worth considering whether a similar approach would work for other anatomical structures - if so, there'd be a nice consistency gain.

**Comment by ybradford** [comment]
I agree that specificity in description of the abnormality is preferred. I would also like this pattern to be available for use, as often authors will say that a particular structure is decreased in size but fail to say exactly how it is decreased in size.

**Comment by srobb1** [comment]
I added the contributors, description from the spreadsheet, and examples to increasedSizeOfAnatomicalEntity.yaml. The same discussions in this thread likely apply to this pattern as well.

Has a consensus been reached for 
- descreasedSizeOfAnatomicalEntity
   - description ? : "abnormally small anatomical structure"??
   - term name ?  : "decreased size of the %s"
   - definition ?  : "A reduction in the size of the %s."
   - synonyms ? :  "small %s"

The inverse is likely to work for increasedSizeOfAnatomicalEntity.

https://github.com/obophenotype/upheno/pull/376
```
pattern_name: increasedSizeOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedSizeOfAnatomicalEntity.yaml
description: "A enlarged entity, like a large anatomical structure.	i.e. HP_0012081 'Enlarged cerebellum'"

contributors:
  - https://orcid.org/0000-0002-9900-7880
  - https://orcid.org/0000-0002-9611-1279
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0003-4148-4606

classes:
  increased size: PATO:0000586
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "increased size of the %s"
  vars:
   - anatomical_entity
     
annotations:
  - annotationProperty: exact_synonym
    text: "enlarged %s"
    vars:
     - anatomical_entity     

def:
  text: "An increase in the size of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('increased size' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```
