### ISSUE TITLE
Review: abnormalBiologicalProcess.yaml

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#373]
added contributors and example term: https://github.com/obophenotype/upheno/pull/372

maybe this one is done?

**Comment by matentzn** [comment]
```
pattern_name: abnormalBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBiologicalProcess.yaml
description: "Any unspecified abnormality of a biological process. i.e. HP_0012647 'Abnormal inflammatory response'"

contributors:
  - https://orcid.org/0000-0002-9900-7880
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0002-1373-1705
  - https://orcid.org/0000-0003-4148-4606

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  biological_process: GO:0008150

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  biological_process: "'biological_process'"
 
name:
  text: "abnormal %s"
  vars:
   - biological_process

def:
  text: "Abnormal %s."
  vars:
    - biological_process

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - biological_process
```
@obophenotype/phenotype-editors

**Comment by LCCarmody** [comment]
Same comment as #367 : Qualifier to has modifier for  RO:0002573

**Comment by matentzn** [comment]
I need a favour which is a bit unlike me, violating my own rigour. 

The current pattern is

```
pattern_name: abnormalBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalBiologicalProcess.yaml
description: "Any unspecified abnormality of a biological process, a specific objective that the organism is genetically programmed to achieve, such as apoptosis or cell proliferation. i.e. HP_0012647 'Abnormal inflammatory response'"

contributors:
- https://orcid.org/0000-0002-9900-7880
- https://orcid.org/0000-0001-9076-6015
- https://orcid.org/0000-0002-3528-5267
- https://orcid.org/0000-0001-5208-3432
- https://orcid.org/0000-0002-1373-1705
- https://orcid.org/0000-0003-4148-4606
- https://orcid.org/0000-0001-7941-2961
classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  biological_process: GO:0008150

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  biological_process: "'biological_process'"
name:
  text: "abnormal %s"
  vars:
  - biological_process

def:
  text: "Abnormal %s."
  vars:
  - biological_process

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
  - biological_process
```

I would like to change the PATO filler of this pattern from 'process quality' to quality: PATO:0000001, because I would really like to exploit its power for reasoning in many of the existing ontologies (that are not yet, and not for a while to come, 100% covered by patterns), but lose a lot of stuff because people have been using many non-process qualities for over a very long time now as qualities for processes. Now the hardliners among us (@dosumis, and me) would say: lets go and fix all those uses and make sure only qualities applicable to processes are used in conjunction with qualities. I would argue that we do not have the resources to do that right now; and the utility of having abnormal processes as they are defined now nestle nicely under our abnormalBiologicalProcess classes is just too tempting.

The most important concrete case is ZP; ZFIN has for many years created very structured high quality EQs, but, not knowing about this limitation, used non-process qualities for processes very often, such as: absent, decreased speed, decreased magnitude, velocity.

@srobb1 @sbello @ybradford @chris-grove @dosumis @mah11 @LCCarmody @nicolevasilevsky 

Of course, if we had the resources, we would really want to use this opportunity to restructure PATO as well, but we dont, and I really need to move this along now. Thanks for your input, I need a comment from everyone here, because this pertains to one of our most hardened patterns.
