### ISSUE TITLE
Review:abnormalMorphologyOfAnatomicalEntity.yaml

### ISSUE THREAD

**Issue by Clare72** [obophenotype/upheno#374]
[abnormalMorphologyOfAnatomicalEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfAnatomicalEntity.yaml)

Given the recent discussions of shape vs morphology, 'abnormal shape' should not be an exact synonym for 'abnormal morphology'. This should either be removed or changed to a narrow/broad synonym.

**Comment by matentzn** [comment]
+1

**Comment by nicolevasilevsky** [comment]
pattern_name: abnormalMorphologyOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalMorphologyOfAnatomicalEntity.yaml
description: ""

classes:
  morphology: PATO:0000051
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "abnormal morphology of %s "
  vars:
   - anatomical_entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "abnormal shape of %s"
    vars:
     - anatomical_entity
  - 
    annotationProperty: exact_synonym
    text: "abnormally shaped %s"
    vars:
     - anatomical_entity     

def:
  text: "Any structural anomaly of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('morphology' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by nicolevasilevsky** [comment]
@obophenotype/phenotype-editors only one more person needs to sign off on this one!

**Comment by chris-grove** [comment]
As per my prior comments, I would keep the exact synonym "abnormal shape of %s" but I would omit "abnormally shaped %s" as an exact synonym. Otherwise, looks good.

**Comment by matentzn** [comment]
```
pattern_name: abnormalMorphologyOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalMorphologyOfAnatomicalEntity.yaml
description: ""

classes:
  morphology: PATO:0000051
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "abnormal morphology of %s "
  vars:
   - anatomical_entity

annotations:
  - annotationProperty: exact_synonym
    text: "abnormal shape of %s"
    vars:
     - anatomical_entity     

def:
  text: "Any structural anomaly of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('morphology' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```
@sbello can you provide a good HUman readable definition for this pattern that clearly distinguishes it from abnormal shape and give your opinion on whether abnormal shape of %s should be kept as a synonym?
