### ISSUE TITLE
Review: abnormallyIncreasedRateOfBehavior.yaml

### ISSUE THREAD

**Issue by Clare72** [obophenotype/upheno#375]
[increasedRateOfBehavior.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/increasedRateOfBehavior.yaml)

I'm not comfortable with defining this as an improvement as it will often mean that the organism is performing worse than controls. For example, increased wandering behavior in larvae usually means that they are eating less of a perfectly good food source (which may not be measured directly to be captured as a 'decreased food intake' phenotype). It is also possible that quality decreases as rate increases, e.g. a male fly may sing his courtship song more quickly, but the female may be less impressed by it!

**Comment by matentzn** [comment]
Yeah, my thoughts exactly; thats why I renamed the pattern from enhancedBehavior to increasedRateOfBehavior, and took the PATO definition for increased rate to describe the pattern. Where do you still see that it is defined as an improvement?

**Comment by Clare72** [comment]
In the text definition

**Comment by matentzn** [comment]
Ah I can see it. Synonym, description and label :P Never look at those. +1 (100%) on the suggestion!

**Comment by Clare72** [comment]
Similar thing for decreased rate being described as 'impaired'

**Comment by nicolevasilevsky** [comment]
pattern_name: increasedRateOfBehavior
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedRateOfBehavior.yaml
description: "Behavior occurs with a higher frequency (more often) than usual (per unit of time)"

classes:
  increased rate: PATO:0000912
  abnormal: PATO:0000460
  behavior process: NBO:0000313

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  behavior_process: "'behavior process'"
 
name:
  text: "Enhanced %s"
  vars:
   - behavior_process

def:
  text: "Enhanced or improved %s."
  vars:
    - behavior_process

equivalentTo:
  text: "'has_part' some ('increased rate' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - behavior_process
    

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
I agree completely with @Clare72 and @matentzn 
Can we just make the name "Abnormally increased rate of %s" instead of "Enhanced %s"?
Also, make the definition "Abnormally increased rate of %s" instead of "Enhanced or improved %s."? Or are we deliberately trying to make the name and definition non-identical?
Otherwise, I'm fine with the pattern.

**Comment by chris-grove** [comment]
Updating ticket:
Updating title to "abnormallyIncreasedRateOfBehavior"

Pattern location as of May 9, 2019:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedRateOfBehavior.yaml

Pattern as of May 9, 2019:
```
pattern_name: abnormallyIncreasedRateOfBehavior
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedRateOfBehavior.yaml
description: "Behavior occurs with a higher frequency (more often) than usual (per unit of time)"

contributors: 
  - https://orcid.org/0000-0001-9076-6015
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0001-5208-3432

classes:
  increased rate: PATO:0000912
  abnormal: PATO:0000460
  behavior process: NBO:0000313

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  behavior_process: "'behavior process'"
 
name:
  text: "Enhanced %s"
  vars:
   - behavior_process

def:
  text: "Enhanced or improved %s."
  vars:
    - behavior_process

equivalentTo:
  text: "'has_part' some ('increased rate' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
- behavior_process
```
