### ISSUE TITLE
review: increasedRateOfBiologicalProcess

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#401]
pattern_name: increasedRateOfBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedRateOfBiologicalProcess.yaml
description: "Increased frequency of a biological process occuring (per some unit of time)."

classes:
  increased rate: PATO:0000912
  abnormal: PATO:0000460
  biological_process: GO:0008150

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  biological_process: "'biological_process'"
 
name:
  text: "increased %s"
  vars:
   - biological_process

def:
  text: "Increased %s."
  vars:
    - biological_process

equivalentTo:
  text: "'has_part' some ('increased rate' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - biological_process

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
As with my comment for https://github.com/obophenotype/upheno/issues/419

I would request that the name and definition change to "Abnormally increased rate of %s" or simply "increased rate of %s"

**Comment by drseb** [comment]
For hpo the part about „abnormally“ is kind of essential and I would prefer to include it.

**Comment by dosumis** [comment]
> For hpo the part about „abnormally“ is kind of essential and I would prefer to include it.

we should have both.

**Comment by chris-grove** [comment]
Updating ticket:
Updating title to "abnormallyIncreasedRateOfBiologicalProcess"

Pattern GitHub location as of May 9, 2019:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedRateOfBiologicalProcess.yaml

Pattern IRI as of May 9, 2019:
http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedRateOfBiologicalProcess.yaml

Pattern as of May 9, 2019:
```
pattern_name: abnormallyIncreasedRateOfBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedRateOfBiologicalProcess.yaml
description: "Abnormally increased frequency of a biological process occuring (per some unit of time)."

contributors:
- https://orcid.org/0000-0001-9076-6015
- https://orcid.org/0000-0001-5208-3432
- https://orcid.org/0000-0003-4148-4606
- https://orcid.org/0000-0002-7356-1779
- https://orcid.org/0000-0002-3528-5267
classes:
  increased rate: PATO:0000912
  abnormal: PATO:0000460
  biological_process: GO:0008150

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  biological_process: "'biological_process'"
name:
  text: "increased %s"
  vars:
  - biological_process

def:
  text: "Increased %s."
  vars:
  - biological_process

equivalentTo:
  text: "'has_part' some ('increased rate' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
  - biological_process
```
