### ISSUE TITLE
review: abnormalHasFewerPartsOfTypeAnatomicalEntity.yaml

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#424]
Should this really be hasFewPartsOfType in something? I thought that is what  HasFewerPartsOfTypeAnatomicalEntityInLocation would be. If we want it as it is currently is, could be have a simplified hasFewPartsOfType with just the part that is fewer and not what it is part of as well? I prefer the format of [abnormalHasExtraPartsOfTypeAnatomicalEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalHasExtraPartsOfTypeAnatomicalEntity.yaml
)

From [abnormalHasFewerPartsOfTypeAnatomicalEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalHasFewerPartsOfTypeAnatomicalEntity.yaml
)
```
equivalentTo:
  text: "'has_part' some ('has fewer parts of type' and ('inheres_in' some %s) and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - whole_anatomical_entity
    - part_anatomical_entity
```

From [abnormalHasFewerPartsOfTypeAnatomicalEntityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalHasFewerPartsOfTypeAnatomicalEntityInLocation.yaml)
```
equivalentTo:
  text: "'has_part' some ('has fewer parts of type' and ('inheres_in' some (%s and ('part_of' some %s))) and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - whole_anatomical_entity
    - part_anatomical_entity
    - location
```

Thanks,
Sofia
