### ISSUE TITLE
review: abnormallyDecreasedRateOfMolecularFunction

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#450]
Pattern location as of May 8, 2019:
http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedRateOfMolecularFunction.yaml

Pattern as of May 8, 2019:
```
pattern_name: abnormallyDecreasedRateOfMolecularFunction
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedRateOfMolecularFunction.yaml
description: ""

contributors: 
  - https://orcid.org/0000-0002-9900-7880
  - https://orcid.org/0000-0002-3528-5267
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0003-4148-4606

classes:
  decreased rate: PATO:0000911
  abnormal: PATO:0000460
  molecular function: GO:0003674

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  molecular_function: "'molecular function'"
 
name:
  text: "decreased %s"
  vars:
   - molecular_function

def:
  text: "Decreased %s."
  vars:
    - molecular_function

equivalentTo:
  text: "'has_part' some ('decreased rate' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - molecular_function

```
