### ISSUE TITLE
review: abnormalAbsenceOfBiologicalProcess

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#456]
Branching off from the designated ticket #330 as that has drifted from the original "absent" pattern discussion.

Pattern location as of May 9, 2019:
http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalAbsenceOfBiologicalProcess.yaml

Pattern as of May 9, 2019:
```
pattern_name: abnormalAbsenceOfBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalAbsenceOfBiologicalProcess.yaml
description: ""

contributors:
  - https://orcid.org/0000-0001-9076-6015
  - https://orcid.org/0000-0001-5208-3432
  - https://orcid.org/0000-0003-4148-4606

classes:
  lacking processual parts: PATO:0001558
  abnormal: PATO:0000460
  biological process: GO:0008150

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  biological_process: "'biological process'"

name:
  text: "absent %s"
  vars:
   - biological_process

def:
  text: "Lack of %s."
  vars:
    - biological_process

equivalentTo:
  text: "'has_part' some ('lacking processual parts' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - biological_process

```
