### ISSUE TITLE
review: abnormallyIncreasedResistanceToChemicalEntity

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#457]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-workshop/abnormallyIncreasedResistanceToChemicalEntity.yaml

```
pattern_name: abnormallyIncreasedResistanceToChemicalEntity.yaml
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedResistanceToChemicalEntity.yaml
description: "A phenotype in which an organism shows increased resistance to a chemical, for example 4-aminosalicylic acid."

contributors:
  - https://orcid.org/0000-0001-9076-6015

classes:
  increased sensitivity toward: PATO:0001549
  abnormal: PATO:0000460
  organism: UBERON:whole organism / <- UBERON should capture single cellular organisms as well
  chemical_entity: CHEBI:000000

relations: 
  inheres_in_part_of: RO:0000000
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical_entity'"

name:
  text: "increased resistance of organism to %s"
  vars:
   - chemical_entity

def:
  text: "Increased resistance of organism to %s."
  vars:
    - chemical_entity

equivalentTo:
  text: "'has_part' some ('increased resistance' and ('inheres_in_part_of' some 'organism') and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity
```

Hey all, this pattern is a very early draft that came out of todays PHIPO call; could you please take a close look.

**Comment by pfey03** [comment]
I would need this pattern (e.g. DDPHENO:0000029 | increased resistance to N-Phenylthiourea)
and as well other related ones, such as
increased sensitivity to ChemicalEntity
and also 
increased resistance/sensitivity to TemperatureChanges 
DDPHENO:0000411 | increased resistance to heat shock
DDPHENO:0000414 | increased sensitivity to heat shock

**Comment by chris-grove** [comment]
I think that:

increased sensitivity toward: PATO:0001549

was meant to be

decreased sensitivity toward: PATO:0001550

OR alternatively

increased resistance to: PATO:0001650

Not sure if "decreased sensitivity toward" and "increased resistance to" are meant to be synonyms?

**Comment by dosumis** [comment]
These should presumably classify under response_to phenotype terms.  But there is no relationship in  PATO between these branches. This should be added. See https://github.com/pato-ontology/pato/issues/244

**Comment by mah11** [comment]
The view from FYPO:

- We have *lots* of chemical sensitivity terms that presumably could use this pattern, and the corresponding 'decreased' and 'normal' patterns, if UBERON:whole organism does include single-celled organisms.

- Like @pyey03, we also have phenotypes of increased, decreased, and normal sensitivity/resistance to non-chemical insults including temperature, UV or gamma radiation, and others.

- re @chris-grove 

> Not sure if "decreased sensitivity toward" and "increased resistance to" are meant to be synonyms?

I have never been able to articulate a useful distinction between "decreased sensitivity toward" and "increased resistance to", fwiw.

- We've extensively discussed where 'response' fits in, and as a result I'm not entirely convinced that 
Many many of the chemical entities that do or don't affect yeast population growth (by far the most commonly assayed form of 'sensitivity') are things that S. pombe wouldn't have a specifically evolved 'response' to, and we have long backed away from characterizing sensitivity or resistance as reflecting an effect on any particular cellular response to a stimulus (cf. ongoing discussions about 'response to' terms in GO, some of which @dosumis may recall, e.g. https://github.com/geneontology/go-ontology/issues/16565).

**Comment by srengel** [comment]
SGD uses the APO and, like Midori and Petra, we have lots of phenotypes of increased, decreased, and normal sensitivity/resistance to both chemical and non-chemical insults including temperature, UV or gamma radiation, and others.

**Comment by chris-grove** [comment]
'inheres in part of' should be "RO:0002314" not "RO:0000000"

Also, 'chemical entity' should be "CHEBI:24431" not "CHEBI:000000"

```
pattern_name: abnormallyIncreasedResistanceToChemicalEntity.yaml
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedResistanceToChemicalEntity.yaml
description: "A phenotype in which an organism shows increased resistance to a chemical, for example 4-aminosalicylic acid."

contributors:
  - https://orcid.org/0000-0001-9076-6015

classes:
  increased resistance to: PATO:0001650
  abnormal: PATO:0000460
  organism: UBERON:whole organism / <- UBERON should capture single cellular organisms as well
  chemical_entity: CHEBI:24431

relations: 
  inheres_in_part_of: RO:0002314
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical_entity'"

name:
  text: "increased resistance of organism to %s"
  vars:
   - chemical_entity

def:
  text: "Increased resistance of organism to %s."
  vars:
    - chemical_entity

equivalentTo:
  text: "'has_part' some ('increased resistance to' and ('inheres_in_part_of' some 'organism') and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity
```
