### ISSUE TITLE
review: abnormalQuantityOfAnatomicalEntity

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#468]
Pattern as of May 29, 2019:

```
pattern_name: abnormalQuantityOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalQuantityOfAnatomicalEntity.yaml
description: "Abnormal number/quantity of anatomical enities. Example, PLANP_0000526,altered number of heads." 

classes:
  altered number of: PATO:0002083
  abnormal: PATO:0000460
  anatomical_entity: UBERON:0001062 

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical_entity'"

name:
  text: "abnormal number of %ss"
  vars:
   - anatomical_entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "altered number of %ss"
    vars:
     - anatomical_entity
  -
    annotationProperty: exact_synonym
    text: "Abnormal count of %ss"
    vars:
     - anatomical_entity

def:
  text: "Any structural anomaly that causes there to be an abnormal number of %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('altered number of' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```

**Comment by chris-grove** [comment]
Comments:
1) the pattern refers to "%ss" in several locations; I imagine that is supposed to be just "%s"
2) Do we need the "Any structural anomaly that causes.." part of the text definition? Can we just say "abnormal number of %s"? There are plenty of cases in which an altered number of anatomical entities is not caused by any structural anomaly, but rather developmental pathways, etc.
3) The EQ statement looks fine

**Comment by chris-grove** [comment]
OK @matentzn clarified the "%ss" issue, so no problem.

I made a change to the textual definition to simply be:

"An abnormal number of %ss."

Here is the current pattern (as of June 5, 2019):

```
pattern_name: abnormalQuantityOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalQuantityOfAnatomicalEntity.yaml
description: "Abnormal number/quantity of anatomical enities. Example, PLANP_0000526, altered number of heads." 

contributors:
  - https://orcid.org/0000-0001-9076-6015

classes:
  altered number of: PATO:0002083
  abnormal: PATO:0000460
  anatomical_entity: UBERON:0001062 

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical_entity'"

name:
  text: "abnormal number of %ss"
  vars:
   - anatomical_entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "altered number of %ss"
    vars:
     - anatomical_entity
  -
    annotationProperty: exact_synonym
    text: "Abnormal count of %ss"
    vars:
     - anatomical_entity

def:
  text: "An abnormal number of %ss."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('altered number of' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
- anatomical_entity
```
