### ISSUE TITLE
review: abnormallyDecreasedNumberOfAnatomicalEntity

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#476]
Pattern as of June 10, 2019
```
pattern_name: abnormallyDecreasedNumberOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedNumberOfAnatomicalEntity.yaml
description: "A decreased number of an anatomical entity, such a decreased number of teeth."

contributors:
  - https://orcid.org/0000-0001-5208-3432

classes:
  decreased amount: PATO:0001997
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

  
annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "Decreased number of %s"
  vars:
   - anatomical_entity

annotations:
  - annotationProperty: exact_synonym
    text: "Reduced number of %s"
    vars:
     - anatomical_entity

def:
  text: "The presence of a reduced number of %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('decreased amount' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity
```

The pattern IRI is malformed. Should be:

http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedNumberOfAnatomicalEntity.yaml

instead of:

http://purl.obolibrary.org/obo/upheno/patterns-dev/http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedNumberOfAnatomicalEntity.yaml

@matentzn 
I can make change and make pull request if you'd like
