### ISSUE TITLE
Multiple TSV supplied exact_synonyms plus an auto generated exact_synonym

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#479]
You can have both an autogenerated syn and manual synonyms from the TSV, or you can use just one.

To have an autogenerate synonym 
  - use `generated_synonyms:` 
  - Do not create an `annotationProperties:` entry in the `annotations` section for your exact_synonym. 

To use synonyms from your TSV use  
 - add `exact_synonym:` section. 
 - This also required you to add your new variable name to `data_list_vars:`.
     - In the example below I used `  exact_syn`.
 - in your TSV use the column header `defined_class_exact_synonym`
 - You can supply a '|' delimited list of syns in your TSB

```
data_list_vars:
  exact_syn: xsd:string

generated_synonyms:
  - text: "%s of %s"
    vars:
     - anatomical_entity
     - anatomical_space

exact_synonym:
  value: exact_syn

```
