### ISSUE TITLE
review: abnormallyIncreasedSensitivityToChemicalEntity

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#485]
Related to (opposite) pattern #457

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-workshop/abnormallyIncreasedSensitivityToChemicalEntity.yaml

```
pattern_name: abnormallyIncreasedSensitivityToChemicalEntity.yaml
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIncreasedSensitivityToChemicalEntity.yaml
description: "A phenotype in which an organism shows increased sensitivity to a chemical, for example 4-aminosalicylic acid."

contributors:
  - https://orcid.org/0000-0001-9076-6015

classes:
  increased sensitivity toward: PATO:0001549
  abnormal: PATO:0000460
  organism: UBERON:whole organism / <- UBERON should capture single cellular organisms as well
  chemical_entity: CHEBI:24431

relations: 
  inheres_in_part_of: RO:0002314
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical_entity'"

name:
  text: "increased sensitivity of organism to %s"
  vars:
   - chemical_entity

def:
  text: "Increased sensitivity of organism to %s."
  vars:
    - chemical_entity

equivalentTo:
  text: "'has_part' some ('increased sensitivity toward' and ('inheres_in_part_of' some 'organism') and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
- chemical_entity
```

Comments and suggestions welcome.
