### ISSUE TITLE
review: abnormallyExpeditedBiologicalProcess

### ISSUE THREAD

**Issue by jseager7** [obophenotype/upheno#492]
This is a proposal for a pattern that is the inverse of '[abnormally delayed biological process](https://github.com/obophenotype/upheno/blob/72f8fe132d5560dba2727c1564e7931f40c4792f/src/patterns/dosdp-dev/abnormallyDelayedBiologicalProcess.yaml)'.

'Expedited' is an antonym of 'delayed', and in this context should be taken to mean a biological process that 'starts _sooner_ than the natural start time or the reference process' (adapting the PATO definition for 'delayed' at [PATO:0000502](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000502)). This pattern is required for numerous terms in [PHIPO](https://github.com/PHI-base/phipo).

Unfortunately, PATO does not seem to have an inverse for the 'delayed' quality &ndash; nothing is shown on the [OLS page](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000502), anyway. Presumably PATO would need to add a term with the opposite meaning of 'delayed' before this pattern can be created. I've been told @mah11 can help with this?

Here's the draft:

```yaml
pattern_name: abnormallyExpeditedBiologicalProcess
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyExpeditedBiologicalProcess.yaml
description: "A biological process which starts sooner than the natural start time or the reference process."

contributors:
  - https://orcid.org/0000-0001-7487-610X

classes:
  expedited: PATO:_______ # no term exists for this quality
  abnormal: PATO:0000460
  biological process: GO:0008150

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  biological_process: "'biological process'"

name:
  text: "expedited %s"
  vars:
   - biological_process

def:
  text: "Expedited %s."
  vars:
    - biological_process

equivalentTo:
  text: "'has_part' some ('expedited' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - biological_process
```
