### ISSUE TITLE
Review: abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation.yaml

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#635]
[abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedLevelOfChemicalEntityWithRoleInLocation.yaml)

I am confused by this pattern. Is the chemical entity supposed to be a variable? The example makes it look like it should be assignable. So either the example needs to change or the eq.

```
equivalentTo:
  text: "'has_part' some ('increased amount' and ('inheres_in' some ('chemical entity' and ('has_role' some %s) and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - role
    - location
```
