### ISSUE TITLE
replace absence pattern using lack_all_parts_of_type; and matching has_fewer_parts_of_type pattern

### ISSUE THREAD

**Issue by dosumis** [obophenotype/upheno#719]
STATUS: Draft proposal

For background see https://docs.google.com/presentation/d/1-FMyAdfQhEyDClfKdDHfeC2LZ5Q-dsP5uY_25rEQ-rI/edit#slide=id.g96675c1a66_0_50

Challenge:  This approach requires punning, which in turn requires declaration of classes as individuals.  Do we need to specify these declarations? Can we rely on DOSDP-tools to deal with this automatically?

### lacks/absence

```yaml
vars: 
 location: "'anatomical_entity'"
 part:  "'anatomical_entity'"

EquivalentTo: 
    text: has_part some 'lacks all parts of type' and inheres_in some %s and towards value %s
     vars:
          - location
          - part
```

labels are a challenge:

1.  Do we need plurals   - absent teeth (?)
2.  In order to get sufficiently specific classification in the morphology branch, location should be as specific as possible.  But we only want the label to mention location if instances of the absent structure (normally) exist outside the specified location.

location: dentition
part:  tooth

=> absent teeth

but 

location: head
part: hair

=> absent hair on head.

Poss solutions: 
 - Two different patterns for each use case + data var to specify part label (=> plural)
 - manual label override in tsv labels (simpler)

### reduced number 

We need two EC axioms - one with existential restriction in order to => classification  by part; one with value restriction to => classification over lacks.

```yaml
vars: 
 location: "'anatomical_entity'"
 part:  "'anatomical_entity'"

logical_axioms: 
   -  
      axiom_type: EquivalentTo
      text: has_part some 'has fewer parts of type' and inheres_in some %s and towards value %s
      vars:
          - location
          - part
  -  
      axiom_type: EquivalentTo
      text: has_part some 'has fewer parts of type' and inheres_in some %s and towards some %s
      vars:
          - location
          - part
```
